import 'package:flutter_firebase/features/chats/data/message.dart';

List<MessageModel> fakeMessages = [
  MessageModel(
    text: "Hello",
    senderId: "user1",
    receiverId: "user2",
    dateTime: DateTime.now(),
    isSenderMsg: true,
  ),
  MessageModel(
    text: "How are you?",
    senderId: "user2",
    receiverId: "user1",
    dateTime: DateTime.now(),
    isSenderMsg: false,
  ),
  MessageModel(
    text: "Good morning",
    senderId: "user1",
    receiverId: "user2",
    dateTime: DateTime.now(),
    isSenderMsg: true,
  ),
  MessageModel(
    text: "Hey there!",
    senderId: "user2",
    receiverId: "user1",
    dateTime: DateTime.now(),
    isSenderMsg: false,
  ),
  MessageModel(
    text: "What's up?",
    senderId: "user1",
    receiverId: "user2",
    dateTime: DateTime.now(),
    isSenderMsg: true,
  ),
  MessageModel(
    text: "I'm fine, thank you!",
    senderId: "user2",
    receiverId: "user1",
    dateTime: DateTime.now(),
    isSenderMsg: false,
  ),
  MessageModel(
    text: "How was your day?",
    senderId: "user1",
    receiverId: "user2",
    dateTime: DateTime.now(),
    isSenderMsg: true,
  ),
  MessageModel(
    text: "It was great!",
    senderId: "user2",
    receiverId: "user1",
    dateTime: DateTime.now(),
    isSenderMsg: false,
  ),
  MessageModel(
    text: "Do you want to go out for dinner?",
    senderId: "user1",
    receiverId: "user2",
    dateTime: DateTime.now(),
    isSenderMsg: true,
  ),
  MessageModel(
    text: "Sure, I'd love to!",
    senderId: "user2",
    receiverId: "user1",
    dateTime: DateTime.now(),
    isSenderMsg: false,
  ),
  MessageModel(
    text: "What time should we meet?",
    senderId: "user1",
    receiverId: "user2",
    dateTime: DateTime.now(),
    isSenderMsg: true,
  ),
  MessageModel(
    text: "Let's meet at 7 pm",
    senderId: "user2",
    receiverId: "user1",
    dateTime: DateTime.now(),
    isSenderMsg: false,
  ),
  MessageModel(
    text: "I'll see you there!",
    senderId: "user1",
    receiverId: "user2",
    dateTime: DateTime.now(),
    isSenderMsg: true,
  ),
  MessageModel(
    text: "Great, can't wait!",
    senderId: "user2",
    receiverId: "user1",
    dateTime: DateTime.now(),
    isSenderMsg: false,
  ),
  MessageModel(
    text: "Have you seen the latest movie?",
    senderId: "user1",
    receiverId: "user2",
    dateTime: DateTime.now(),
    isSenderMsg: true,
  ),
  MessageModel(
    text: "Not yet, but I heard it's good",
    senderId: "user2",
    receiverId: "user1",
    dateTime: DateTime.now(),
    isSenderMsg: false,
  ),
  MessageModel(
    text: "We should watch it together",
    senderId: "user1",
    receiverId: "user2",
    dateTime: DateTime.now(),
    isSenderMsg: true,
  ),
  MessageModel(
    text: "Sounds like a plan!",
    senderId: "user2",
    receiverId: "user1",
    dateTime: DateTime.now(),
    isSenderMsg: false,
  ),
  MessageModel(
    text: "I have tickets for the concert",
    senderId: "user1",
    receiverId: "user2",
    dateTime: DateTime.now(),
    isSenderMsg: true,
  ),
  MessageModel(
    text: "That's awesome, I can't wait!",
    senderId: "user2",
    receiverId: "user1",
    dateTime: DateTime.now(),
    isSenderMsg: false,
  ),
];

// Total of 30 items in the list