// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh3wL_GoedIv8Z9kDgLZ7hiRhBktiF9Go',
    appId: '1:698398788207:android:6784571e60eaa5fa001b9a',
    messagingSenderId: '698398788207',
    projectId: 'chatty-dev990',
    databaseURL: 'https://chatty-dev990-default-rtdb.firebaseio.com',
    storageBucket: 'chatty-dev990.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-Nu5A5rIpVkNjGqBVe9yjrA5-BcvIEyk',
    appId: '1:698398788207:ios:208b27920253c7d4001b9a',
    messagingSenderId: '698398788207',
    projectId: 'chatty-dev990',
    databaseURL: 'https://chatty-dev990-default-rtdb.firebaseio.com',
    storageBucket: 'chatty-dev990.appspot.com',
    androidClientId: '698398788207-ldfjk1f36jbsfjiom1lj0sjj4qr2o56s.apps.googleusercontent.com',
    iosClientId: '698398788207-k46qie2p2lq8m8juvc0hendvq7ac191t.apps.googleusercontent.com',
    iosBundleId: 'dev.eslammongy.chatty',
  );

}